# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Wildflower
email: "info@wildflowersalonmpls.com"
description: >- # this means to ignore newlines until "baseurl:"
  An Eco Salon
# baseurl: "/wildflower" # the subpath of your site, e.g. /blog
url: "http://duncan-d.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
vagaro_link: 'https://www.vagaro.com/wildflowersalonmpls'
phone_number: '612-438-7143' # 612-710-9003 isn't the real phone number...

repository: "wildflowersalon/wildflower"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# A list of the pages to display in the navigation bar
header_pages:
# no links for about or services until they're populated
 - about.md # i'm thinking this will be general info and/or mission statement and/or a what is an eco salon
 #- services.md
 - stylists.md

collections:
  stylists:
    order: 
      - nikol.md
      - laura.md
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
